export const wordListData = [
  {
    upper: "A",
    lower: "a",
    clr: "#a8df65",
    name: "apple",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "B",
    lower: "b",
    clr: "#fe8a71",
    name: "ball",
    img: require("../../../assets/words/b.jpg"),
  },
  {
    upper: "C",
    lower: "c",
    clr: "#ffd31d",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "D",
    lower: "d",
    clr: "#ff5200",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "E",
    lower: "e",
    clr: "#43d8c9",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "F",
    lower: "f",
    clr: "#f6acc8",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "G",
    lower: "g",
    clr: "#cf7500",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "H",
    lower: "h",
    clr: "#543864",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "I",
    lower: "i",
    clr: "#00bcd4",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "J",
    lower: "j",
    clr: "#8db1ab",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "K",
    lower: "k",
    clr: "#363062",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "L",
    lower: "l",
    clr: "#f6d186",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "M",
    lower: "m",
    clr: "#fbcffc",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "N",
    lower: "n",
    clr: "#a8df65",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "O",
    lower: "o",
    clr: "#98d6ea",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "P",
    lower: "p",
    clr: "#feb72b",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "Q",
    lower: "q",
    clr: "#fa163f",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "R",
    lower: "r",
    clr: "red",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "S",
    lower: "s",
    clr: "#4f98ca",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "T",
    lower: "t",
    clr: "#f67280",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "U",
    lower: "u",
    clr: "#3fc5f0",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "V",
    lower: "v",
    clr: "#e25822",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "W",
    lower: "w",
    clr: "#9852f9",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "X",
    lower: "x",
    clr: "#01d28e",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "Y",
    lower: "y",
    clr: "grey",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "Z",
    lower: "z",
    clr: "gold",
    img: require("../../../assets/words/a.jpg"),
  },
];
