export const wordListData = [
  {
    upper: "A",
    lower: "a",
    clr: "#a8df65",
    name: "apple",
    img: require("../../../assets/words/a.jpg"),
  },
  {
    upper: "B",
    lower: "b",
    clr: "#fe8a71",
    name: "ball",
    img: require("../../../assets/words/b.jpg"),
  },
  {
    upper: "C",
    lower: "c",
    clr: "#ffd31d",
    name: "cup",
    img: require("../../../assets/words/c.png"),
  },
  {
    upper: "D",
    lower: "d",
    clr: "#ff5200",
    name: "dog",
    img: require("../../../assets/words/d.png"),
  },
  {
    upper: "E",
    lower: "e",
    clr: "#43d8c9",
    name: "elephant",
    img: require("../../../assets/words/e.png"),
  },
  {
    upper: "F",
    lower: "f",
    clr: "#f6acc8",
    name: "fish",
    img: require("../../../assets/words/f.png"),
  },
  {
    upper: "G",
    lower: "g",
    clr: "#cf7500",
    name: "giraffe",
    img: require("../../../assets/words/g.png"),
  },
  {
    upper: "H",
    lower: "h",
    clr: "#543864",
    name: "hat",
    img: require("../../../assets/words/h.png"),
  },
  {
    upper: "I",
    lower: "i",
    clr: "#00bcd4",
    name: "igloo",
    img: require("../../../assets/words/i.jpg"),
  },
  {
    upper: "J",
    lower: "j",
    clr: "#8db1ab",
    name: "jelly fish",
    img: require("../../../assets/words/j.jpg"),
  },
  {
    upper: "K",
    lower: "k",
    clr: "#363062",
    name: "kangaroo",
    img: require("../../../assets/words/k.jpg"),
  },
  {
    upper: "L",
    lower: "l",
    clr: "#f6d186",
    name: "loin",
    img: require("../../../assets/words/l.jpg"),
  },
  {
    upper: "M",
    lower: "m",
    clr: "#fbcffc",
    name: "monkey",
    img: require("../../../assets/words/m.png"),
  },
  {
    upper: "N",
    lower: "n",
    clr: "#a8df65",
    name: "nest",
    img: require("../../../assets/words/n.png"),
  },
  {
    upper: "O",
    lower: "o",
    clr: "#98d6ea",
    name: "octopus",
    img: require("../../../assets/words/o.png"),
  },
  {
    upper: "P",
    lower: "p",
    clr: "#feb72b",
    name: "pigeon",
    img: require("../../../assets/words/p.png"),
  },
  {
    upper: "Q",
    lower: "q",
    clr: "#fa163f",
    name: "queen",
    img: require("../../../assets/words/q.png"),
  },
  {
    upper: "R",
    lower: "r",
    clr: "red",
    name: "rocket",
    img: require("../../../assets/words/r.png"),
  },
  {
    upper: "S",
    lower: "s",
    clr: "#4f98ca",
    name: "snake",
    img: require("../../../assets/words/s.jpeg"),
  },
  {
    upper: "T",
    lower: "t",
    clr: "#f67280",
    name: "tiger",
    img: require("../../../assets/words/t.jpg"),
  },
  {
    upper: "U",
    lower: "u",
    clr: "#3fc5f0",
    name: "unicorn",
    img: require("../../../assets/words/u.png"),
  },
  {
    upper: "V",
    lower: "v",
    clr: "#e25822",
    name: "vulture",
    img: require("../../../assets/words/v.jpg"),
  },
  {
    upper: "W",
    lower: "w",
    clr: "#9852f9",
    name: "whale",
    img: require("../../../assets/words/w.jpg"),
  },
  {
    upper: "X",
    lower: "x",
    clr: "#01d28e",
    name: "x-ray",
    img: require("../../../assets/words/x.png"),
  },
  {
    upper: "Y",
    lower: "y",
    clr: "grey",
    name: "yatch",
    img: require("../../../assets/words/y.jpg"),
  },
  {
    upper: "Z",
    lower: "z",
    clr: "gold",
    name: "zebra",
    img: require("../../../assets/words/z.png"),
  },
];
